baseURL = "英桥在干什么吖.我爱你"
languageCode = "en-us"
title = "英桥在干什么吖"
theme = "yinyang"
DefaultContentLanguage = "cn"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
guessSyntax = true
noClasses = true
style = "monokai"
tabWidth = 2

[author]
name = "Qiao"
homepage = "https://github.com/Yingqiao1998"

[languages]
# [languages.en]
# contentDir = "content/en"
# languageName = "English"
# weight = 1
[languages.cn]
contentDir = "content/cn"
languageName = "Chinese"
weight = 2

[params]
mainSections = ["posts"]
headTitle = "小桥在干什么吖"
description = "那一天的忧郁,忧郁起来 那一天的寂寞,寂寞起来(手动流泪)"
disqus = "Qiao"                               # disqus account name
extraHead = ''

# [[params.socials]]
# name = "About Me"
# link = "https://github.com/Yingqiao1998"
[[params.socials]]
name = "Github"
link = "https://github.com/Yingqiao1998"
postHeaderContent = ""
# postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []
